### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by debe** [amdeb/amdeb-amazon#1]
Dear developer colleague,
is amdeb-amazon already in a usable state? I desperately need something to sync orders and customers to odoo. Is there a way to get in tough with you other than opening issues :-).

best regards,
-dennis

**Comment by YingLiu4203** [comment]
Dennis,
Thank you for your interests in this project. It is under active development and far from a stable state. The product data sync is near completion. Order and customer sync are not started.
