### ISSUE TITLE
NotImplementedError: gevent is only usable from a single thread

### ISSUE THREAD

**Issue by raDDe** [amdeb/amdeb-amazon#2]
Hi there,

I tried to install your app and got there error in my terminal:

"NotImplementedError: gevent is only usable from a single thread"

Do you change something in your config, or installed some python lib I don't have? I installed the gevent lib and the dependencies, but this didn't help me.

Do you have any suggestion how to fix this problem?

thanks and best regards

Sebastian

**Comment by YingLiu4203** [comment]
Looks like an Odoo issue. This addon is under active development and is far from stable.
